"""Add user_id to UserAnswer

Revision ID: 7e61c8a28eb5
Revises: b4a93c50a6d4
Create Date: 2025-03-23 19:52:13.410177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e61c8a28eb5'
down_revision = 'b4a93c50a6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_quiz', ['user_id', 'quiz_id'])

    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_quiz', type_='unique')

    # ### end Alembic commands ###
