"""empty message

Revision ID: b4a93c50a6d4
Revises: 
Create Date: 2025-03-20 02:07:10.295703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a93c50a6d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
